---
test:
  build: "."
  dockerfile: Dockerfile.ci
  working_dir: "/app"
  volumes:
  - "./vendor/bundle:/usr/local/bundle"
  - "$CIRCLE_TEST_REPORTS/rspec:$HOME/.rspec_reports"
  environment:
    RACK_ENV: test
    DB_USERNAME: postgres
    DB_HOST: postgresql
    DB_PORT: '5432'
  links:
  - postgresql
postgresql:
  image: postgres:10.6
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: ''
