version: '3.2'

services:
  postgresql:
    image: postgres:10.6
    ports:
      - 5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ''

  redis:
    image: redis
    ports:
      - 6379
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
