production:
  :concurrency: 1
:queues:
  - default
  - ledger_transaction
# :schedule:
  #  an_scheduled_task:
  #    cron: '0 * * * * *'  # Runs once per minute
  #    class: ExampleJob
  #    args: ['a', 'b']
